### ISSUE TITLE
Build fails on both Android and iOS on Flutter 1.22

### ISSUE THREAD

**Issue by magicleon94** [simpleclub/firebase_rest_auth#13]
Hi, I've been using your plugin referencing your fork in my Flutter application.

My `pubspec.yaml` dependency looks like this:
```
  firebase_core: ^0.5.0
  firebase_auth:
    git:
      url: https://github.com/simpleclub-extended/flutterfire
      path: packages/firebase_auth/firebase_auth
      ref: firebase-auth/firebase-rest-auth
```

Today I've tried to build again but got the following error:

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
../.pub-cache/git/flutterfire-9742a75705d8d66ca4a0745b72c230dfe100b625/packages/firebase_auth/firebase_auth/lib/src/recaptcha_verifier.dart:33:54: Error: No named parameter with the name 'parameters'.
          _factory.delegateFor(container: container, parameters: parameters));
                                                     ^^^^^^^^^^         
                                                                        
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/Users/antonellogalipo/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 904
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildDebug'.              
> Process 'command '/Users/antonellogalipo/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 16s                                                     
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        17,6s
Exception: Gradle task assembleDebug failed with exit code 1
```

I've tried `flutter pub repair`, `flutter clean` and stuff but nothing seems to change.

The only thing that's changed is that I've upgraded to Flutter 1.22 on the stable channel:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale it-IT)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.2)
[✓] Connected device (1 available)

• No issues found!
```

I have no idea on how to fix this, some help would be much appreciated... 

Thank you for your time!

**Comment by CiriousJoker** [comment]
Same here. You can fix this by forking the firebase_auth project and commenting out the recaptcha function. Definitely not optimaly, but fixed the error

**Comment by magicleon94** [comment]
I'm kinda feeling stupid here but I need some hints. You mean forking the original flutterfire or the simple club one?

**Comment by CiriousJoker** [comment]
[This project](https://github.com/simpleclub-extended/flutterfire/tree/firebase-auth/firebase-rest-auth) is a fork of firebase-auth that already references firebase_rest_auth where necessary. Since simpleclub-extended is not going to change that often (and for debugging reasons), I cloned simpleclub-extended locally and referenced that inside my pubspec.yaml.
That means, I have a local folder where I can change all the files, so I just commented out the part that breaks and it works now.

In general though, it's probably better to just do a custom fork as mentioned in the readme until simpleclub-extended is updated to the newest firebase-extended.

**Comment by magicleon94** [comment]
Well, I've forked simple club-extended/flutterfire and then made this change:
https://github.com/magicleon94/flutterfire/commit/97dc09a25446b2d19f2f47e48be5abe76322409c

And changed the referent in my project like this:
```
  firebase_auth:
    git:
      url: https://github.com/magicleon94/flutterfire
      path: packages/firebase_auth/firebase_auth
      ref: firebase-auth/firebase-rest-auth
```

But the error remains the same. What am I missing?

**Comment by magicleon94** [comment]
Update: referencing this locally works, so it's maybe a cache problem

**Comment by magicleon94** [comment]
Yup, it's a cache problem. I'm now referencing the magicleon94/flutterfire fork and it now builds on both Android and iOS. Thank you very much for your support! I'm leaving this open hoping for an official fix!

**Comment by CiriousJoker** [comment]
You can use `flutter pub upgrade`.
Afaik that forces a reload but I could be wrong

**Comment by Sese-Schneider** [comment]
@CiriousJoker @magicleon94 I will update everything in a few days.
Unfortunately due to a lot of changes made with the repo by firebase, I can't do this as quickly as I'd like to.
If you have a working solution with the current master of FirebaseExtended/flutterfire merged in, a pull request would be awesome 👍

**Comment by CiriousJoker** [comment]
Sorry, my workaround literally just consisted of me removing unused functionality. It does work, but I'd rather not make a PR for this..

**Comment by Sese-Schneider** [comment]
@CiriousJoker @magicleon94 I've updated the package and simpleclub-extended/FlutterFire to the newest versions of the package, federated plugin structure and Flutter.

Please check if it works
