### ISSUE TITLE
This repo might be no longer needed

### ISSUE THREAD

**Issue by CiriousJoker** [simpleclub/firebase_rest_auth#14]
https://github.com/FirebaseExtended/auth-without-play-services/pull/12#issuecomment-717817309

Non play store devices are supported as of v20

https://firebase.google.com/support/release-notes/android#auth_v20-0-0

**Comment by creativecreatorormaybenot** [comment]
Yes, that is correct :) This repo is going to be obsolete once the Flutter plugin is updated.

**Comment by Sese-Schneider** [comment]
@CiriousJoker as soon as this is available on flutter, I'll archive this repository. I'm very happy that Google took this step! (less maintenance for us)
Thank you for your contributions to this project!
