### ISSUE TITLE
Danke.

### ISSUE THREAD

**Issue by CiriousJoker** [simpleclub/firebase_rest_auth#9]
Bevor ich andere issues erstelle, wollte ich erstmal danke sagen. Danke für die Hilfe beim Abitur, dann 4 Mathe-Semester und jetzt für das package.

Euch wird man echt nicht los 😆

**Comment by creativecreatorormaybenot** [comment]
❤️

**Comment by Sese-Schneider** [comment]
Mega cool, dass wir dich sowohl in der Schule als auch später im Studium beim Lernen unterstützen durften. Alles Gute dir! 💪
